version: 2.1

jobs:
  build:
    docker:
      - image: node:latest
    working_directory: ~/repo
    steps:
      - checkout
      - run: npm install
      - run: hexo generate

workflows:
  deploy-blog-workflow:
    jobs:
      - build
