version: 2.1

jobs:
  build:
    docker:
      - image: node:latest
    working_directory: $CIRCLE_WORKING_DIRECTORY
    steps:
      - checkout
      - run: npm install -g npm
      - run: npm install -g hexo-cli
      - run: hexo generate
  deploy:
    docker:
      - image: node:latest
    working_directory: $CIRCLE_WORKING_DIRECTORY/zhengminhui.github.io 
    steps:
      - checkout
      - run:
          name: Install Hexo CLI
          command: |
            npm install hexo-cli -g
      - attach_workspace:
          at: $CIRCLE_WORKING_DIRECTORY/zhengminhui.github.io 
      - add_ssh_keys:
          fingerprints:
            - "7e:0d:09:19:ed:19:95:d6:2f:b4:72:03:63:d0:4b:5f"
      - run:
          name: Deploy website
          command: |
            echo $PWD
            echo 'start deploy'
      - run: 
          name: generate
          command: hexo generate
      - run: 
          name: deploy static
          command: hexo deploy
      - run: 
          name: clean static
          command: hexo clean
      - run:
          name: push to master
          command: |
            git config --global user.name "zhengminhui"
            git config --global user.email "zhmh1025@hotmail.com"
            git checkout -f master
            git add .
            git commit --allow-empty -m "Automatic commit from CircleCI [skip ci]"
            git push -u origin main
      - run: echo 'successfully finished'
workflows:
  deploy-blog-workflow:
    jobs:
      - build
      - deploy:
          requires:
             - build
